# Generated by Django 5.2.4 on 2025-07-04 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPData',
            fields=[
                ('OTPDataID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OTP', models.CharField(max_length=6)),
                ('IsValid', models.BooleanField(default=True)),
                ('ValidDateTill', models.DateField()),
                ('ValidTimeTill', models.TimeField()),
                ('OTPUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OTPData',
            },
        ),
    ]
