# Generated by Django 5.2.4 on 2025-07-04 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('UsageFrequency', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Cagegory',
            },
        ),
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('ContextID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('SourceType', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('note', 'Note')], max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('InSights', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250)),
                ('Desc', models.TextField()),
                ('PriorityScore', models.FloatField(default=0.0)),
                ('DeadLine', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
