# Generated by Django 5.2.4 on 2025-07-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Category',
        ),
        migrations.DeleteModel(
            name='ContextEntry',
        ),
        migrations.RemoveField(
            model_name='task',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
